//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Teleport : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Tele
        {
            get
            {
                return SteamVR_Actions.teleport_Tele;
            }
        }
        
        public virtual SteamVR_Action_Boolean grabitem
        {
            get
            {
                return SteamVR_Actions.teleport_grabitem;
            }
        }
        
        public virtual SteamVR_Action_Vector2 NewAction
        {
            get
            {
                return SteamVR_Actions.teleport_NewAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.teleport_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.teleport_SnapTurnRight;
            }
        }
    }
}
